// Generated by CoffeeScript 1.6.1
(function() {
  var module;

  module = angular.module('taggedStuff.filters', []);

  module.filter('interpolate', [
    'version', function(version) {
      return function(text) {
        return String(text).replace(/\%VERSION\%/mg, version);
      };
    }
  ]);

  module.filter('timestamp', [
    '$filter', function($filter) {
      var dateFilter;
      dateFilter = $filter('date');
      return function(ts) {
        return dateFilter(ts, 'yyyy-MM-dd HH:mm:ss');
      };
    }
  ]);

}).call(this);
