// Generated by CoffeeScript 1.6.1
(function() {
  var l, module;

  module = angular.module('taggedStuff.services', []);

  module.value('version', '0.2');

  l = function(o) {
    return console.log(o);
  };

  module.factory('baseRestPath', [
    '$window', function($window) {
      var path;
      path = $window.location.pathname;
      return (path.substring(0, path.lastIndexOf('/app'))) + '/rest/';
    }
  ]);

  module.factory('entityServiceFactory', [
    '$http', 'baseRestPath', function($http, baseRestPath) {
      return function(entityName) {
        var basePath, errorLogger, pathWithId;
        basePath = baseRestPath + 'entity/' + entityName + '/';
        pathWithId = function(id) {
          return basePath + id;
        };
        errorLogger = function(data, status, headers, config) {
          return l([data, status, headers, config]);
        };
        return {
          query: function(params, targetArray) {
            var promise;
            promise = $http({
              method: 'GET',
              url: basePath,
              params: params
            });
            if (angular.isArray(targetArray)) {
              promise.success(function(data) {
                targetArray.length = 0;
                return targetArray.push.apply(targetArray, data.result);
              });
            }
            promise.error(errorLogger);
            return promise;
          },
          save: function(entity) {
            var promise, request;
            request = {
              data: entity,
              headers: {
                'Content-Type': 'application/json'
              }
            };
            if (entity.id) {
              request.method = 'PUT';
              request.url = pathWithId(entity.id);
            } else {
              request.method = 'POST';
              request.url = basePath;
            }
            promise = $http(request);
            promise.success(function(data) {
              return angular.copy(data, entity);
            });
            promise.error(errorLogger);
            return promise;
          }
        };
      };
    }
  ]);

  module.factory('tagService', [
    'entityServiceFactory', function(entityServiceFactory) {
      return entityServiceFactory('tag');
    }
  ]);

  module.factory('entryService', [
    'entityServiceFactory', function(entityServiceFactory) {
      return entityServiceFactory('entry');
    }
  ]);

  module.factory('searchService', [
    '$rootScope', function($rootScope) {
      return {
        search: function(searchString) {
          return $rootScope.$broadcast('searchService.executeSearch', searchString);
        },
        addListener: function(scope, callback) {
          return scope.$on('searchService.executeSearch', function(event, searchString) {
            return callback(searchString);
          });
        }
      };
    }
  ]);

}).call(this);
